name=StemBot
version=1.0.0
author=Otto
maintainer=Blockzie
sentence=StemBot humanoid robot library for Otto Bot.
paragraph=Servo control, gestures, sounds and movement for Otto / StemBot robots.
category=Device Control
architectures=*
includes=StemBot.h
